### ISSUE TITLE
Babel 6

### ISSUE THREAD

**Issue by billybonks** [rwjblue/ember-decorators#96] opened 2017-05-26 17:44 UTC
Struggling to get this to work with ember-cli 2.14 and Babel 6 I tried various permutations and, the instructions on the readme

![image](https://cloud.githubusercontent.com/assets/1640136/26505866/f7c98c8c-427c-11e7-9d5b-70105afb66cd.png)

I followed the instructions

![image](https://cloud.githubusercontent.com/assets/1640136/26505885/0affcd34-427d-11e7-9d6d-930a0be5c833.png)

![image](https://cloud.githubusercontent.com/assets/1640136/26505910/1c04003c-427d-11e7-8e9b-31e883f6c213.png)

**Comment by wooandoo** [comment] 2017-06-09 07:34
Hello,

I had the same error in **MY ADDON** because I didn't add the configuration in the index.js:
```js
init: function(app) {
    this._super.init && this._super.init.apply(this, arguments);

    this.options = this.options || {};
    this.options.babel = this.options.babel || {};
    this.options.babel.plugins = this.options.babel.plugins || [];

    if (this.options.babel.plugins.indexOf('transform-decorators-legacy') === -1) {
      this.options.babel.plugins.push('transform-decorators-legacy');
    }
  }
```

with the code above, all work nice ! ;-)

are you in a same situation ?

Frédéric

**Comment by billybonks** [comment] 2017-06-19 03:23
@wooandoo this did not solve my issue :<

**Comment by rwjblue** [comment] 2017-06-21 13:41
@billybonks - Can you provide a demo repo that we can use to identify the issue?

**Comment by NullVoxPopuli** [comment] 2017-06-25 01:08
I have one: https://gitlab.com/precognition-llc/aeonvera-ui/tree/ember-2.13

**Comment by rwjblue** [comment] 2017-07-02 16:06
@NullVoxPopuli - Thank link results in a 404.

In general, this does work, I just need a demo repo so I can try to dig into what is going on specifically...

**Comment by NullVoxPopuli** [comment] 2017-07-02 16:13
@rwjblue I merged the branch, as I decided to go-ahead with the 2.13 upgrade and add the `: null`s to everything that I didn't feel like converting to an es6 class.

here is the main branch: https://gitlab.com/precognition-llc/aeonvera-ui/tree/master
I currently don't have any issues with the decorators using the `: null` addition, even though I don't like it. haha

**Comment by rwjblue** [comment] 2017-07-02 16:22
Ah, I see.  Thanks for confirming that it is working (generally speaking).  I agree that the `null` thing is annoying, but I do understand why that change was made.  In the long run, I think classes are the right path forward but we have some things to work out in Ember around specific edge cases first...

**Comment by rwjblue** [comment] 2017-07-03 13:11
OK, I'm going to close this now as there are a number of folks that have confirmed it is working properly in Babel 6 (with some notable exceptions).  

I'm happy to reopen with a reproduction...

**Closed by rwjblue** 2017-07-03 13:11 UTC
